# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e037ac63f95aabb5bbe5a51f94a285cb20558f46774536ff70c60cf67d7f265f06355a1dde750ccdfa27c6a3176d4f40939cf0a4b7e7c4ce471de3a73a614ae

test:
  secret_key_base: 6dfe275679df7453b86afc1db5aa0c734a202e204c61f4b4517d82e1e5160537e672888bc4e2d0b979e48bf9c6acb67cc3cf49406e87681bcc1ac749d43fde93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
